USE reto_asturias_activa;

UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Ruta_del_cares.jpg' WHERE name = 'Ruta del Cares';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Senda_del_Oso.jpg' WHERE name = 'Senda del Oso';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Vaca_Lagos_de_Covadonga.jpg' WHERE name = 'Lagos de Covadonga';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Ruta_de_las_Xanas.jpg' WHERE name = 'Ruta de las Xanas';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Llanes-20121102-00132.jpg' WHERE name = 'Camin Encantau';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Pico-pienzu.jpg' WHERE name = 'Subida al Picu Pienzu';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Cascada_ruta_del_Alba.jpg' WHERE name = 'Ruta del Alba';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/R%C3%ADo_Esva.JPG' WHERE name = 'Hoces del Esva';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/CUERIGO._Aller%2C_Asturias.jpg' WHERE name = 'Foces del Pino';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Bra%C3%B1a_de_Mumian%2CSomiedo%2C_Asturias_-_panoramio.jpg' WHERE name = 'Brana de Mumian';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Lago_del_Valle%2C_Somiedo_%2834015536670%29.jpg' WHERE name = 'Lago del Valle';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Capilla_Medieval_del_Monsacro-Morcin%2C_Asturias.PNG' WHERE name = 'Pico Monsacro';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Cascada_de_Oneta.jpg' WHERE name = 'Cascadas de Oneta';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Llanes-20121102-00133.jpg' WHERE name = 'Bufones de Pria';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Puerto_de_Llanes.jpg' WHERE name = 'Senda Costera de Llanes';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/GIJ%C3%93N.JPG' WHERE name = 'Senda del Cervigon';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Cabo_Pe%C3%B1as%2C_Asturias.jpg' WHERE name = 'Cabo Penas Circular';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/La_focella_-_panoramio.jpg' WHERE name = 'Camin Real de la Mesa';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Panor%C3%A1mica_del_alto_de_L%27Angliru.jpg' WHERE name = 'Subida al Angliru';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Pe%C3%B1a_Mea_Ojo_de_Buey.JPG' WHERE name = 'Pena Mea desde Les Campes';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Bosque_de_Muniellos_01.JPG' WHERE name = 'Ruta del Castaneu de Pombarinos';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Reserva_Natural_Integral_de_Muniellos_%28Asturias%2C_Espa%C3%B1a%29_18.JPG' WHERE name = 'Bosque de Muniellos - Tablizas';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Ceceda_%28Nava%2C_Asturias%29.jpg' WHERE name = 'Foces del Rio Pendon';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Nacimiento_del_r%C3%ADo_Nora.jpg' WHERE name = 'Senda Fluvial del Nora';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Monte_Naranco.jpg' WHERE name = 'Miradores del Naranco';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Fuentes_%28Villaviciosa%2C_Asturias%29.jpg' WHERE name = 'Ruta de los Molinos de Villaviciosa';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Barres%2C_Castropol%2C_Asturias.jpg' WHERE name = 'Cascada del Cioyo';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/R%C3%ADa_de_Navia.jpg' WHERE name = 'Senda Costera Naviega';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Salas_%28Salas%2C_Asturias%29.jpg' WHERE name = 'Branas Vaqueiras de Salas';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Telledo_%28Lena%2C_Asturias%29.jpg' WHERE name = 'Cuetu Arbas';
UPDATE routes SET cover_image = 'https://commons.wikimedia.org/wiki/Special:FilePath/Pe%C3%B1a_Ubi%C3%B1a.jpg' WHERE name = 'Pena Ubina desde Tuiza';
